POST http://localhost:3001/api/messages
Content-Type: application/json

{
    "name": "Marjatta",
    "phoneNumber": "040123456",
    "email": "example@email.com",
    "content": "This is a test message"
}